#!/bin/bash

if [ -z "${HOST_USER}" ]; then
  echo "ERROR: We need HOST_USER to be set!"; exit 100
fi

if [ -z "${HOST_UID}" ]; then
    echo "ERROR: We need HOST_UID be set" ; exit 100
fi

if [ -z "${HOST_GID}" ]; then
    echo "ERROR: We need HOST_GID be set" ; exit 100
fi

if [ -z "${HOST_GROUP}" ]; then
    echo "ERROR: We need HOST_GROUP be set" ; exit 100
fi

groupadd -g ${HOST_GID} ${HOST_GROUP} 

useradd ${HOST_USER} --shell /bin/bash --create-home \
	--uid ${HOST_UID} --gid ${HOST_GID}

echo ${HOST_USER} ${HOST_UID} ${HOST_GID}
ls /home

echo 'ALL ALL = (ALL) NOPASSWD: ALL' >> /etc/sudoers

chown -R ${HOST_UID}:${HOST_GID} /home/${HOST_USER}

# switch to current user
su "${HOST_USER}"

# enter to shell
exec /bin/bash
